# Generated by Django 5.2.3 on 2025-06-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_event_subscriber_alter_notice_notice_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
