# Generated by Django 5.2.3 on 2025-06-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_event_completed_at_event_is_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="notices/"),
        ),
    ]
