# Generated by Django 5.2.4 on 2025-08-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_event_options_event_end_date_event_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('applying_for_grade', models.IntegerField()),
                ('previous_school', models.CharField(max_length=200)),
                ('previous_grade', models.IntegerField()),
                ('previous_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('father_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(max_length=100)),
                ('father_phone', models.CharField(max_length=15)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_occupation', models.CharField(max_length=100)),
                ('mother_phone', models.CharField(max_length=15)),
                ('student_photo', models.ImageField(upload_to='admissions/photos/')),
                ('previous_marksheet', models.FileField(upload_to='admissions/documents/')),
                ('transfer_certificate', models.FileField(upload_to='admissions/documents/')),
                ('application_id', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWING', 'Under Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
