# Generated by Django 5.2.4 on 2025-08-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='faculty/photos/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('SCIENCE', 'Science'), ('MATHEMATICS', 'Mathematics'), ('ENGLISH', 'English'), ('NEPALI', 'Nepali'), ('SOCIAL', 'Social Studies'), ('COMPUTER', 'Computer Science'), ('ACCOUNTS', 'Accounts'), ('EDUCATION', 'Education'), ('OTHER', 'Other')], max_length=20)),
                ('teaching_levels', models.JSONField(help_text='List of teaching levels')),
                ('qualifications', models.TextField()),
                ('experience_years', models.PositiveIntegerField()),
                ('bio', models.TextField(blank=True)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('achievements', models.TextField(blank=True)),
                ('joining_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Faculty Members',
                'ordering': ['department', 'full_name'],
            },
        ),
    ]
